# Vagrant configuration for local development environment
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "dsti-devops"

  config.vm.synced_folder "../", "/vagrant",
                          type: "virtualbox",
                          mount_options: ["dmode=775", "fmode=664"]

  config.vm.network "forwarded_port", guest: 3000, host: 3000
  # static IP for the VM you can change it as needed
  config.vm.network "private_network", ip: "192.168.56.42"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/site.yml"
    ansible.become = true
  end
end
